# Generated by Django 5.0.6 on 2024-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
                ('report_id', models.IntegerField()),
            ],
        ),
    ]
