# Generated by Django 5.0.6 on 2024-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_password', models.CharField(max_length=255)),
                ('visitor_phonenumber', models.CharField(max_length=15)),
            ],
        ),
    ]
