# Generated by Django 5.0.6 on 2024-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_id',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_password',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_phonenumber',
        ),
        migrations.AddField(
            model_name='visitor',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
