# Generated by Django 5.0.6 on 2024-06-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_visitor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
