# Generated by Django 5.0.6 on 2024-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='phone_number',
            field=models.IntegerField(default='unkown'),
            preserve_default=False,
        ),
    ]
