# Generated by Django 5.0.6 on 2024-06-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_visitor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='phone_number',
        ),
    ]
