# Generated by Django 5.0.6 on 2024-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_visitor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='name',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
